name: Java CI with Gradle

on: [push]
jobs:

  jdk16:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Set Artifact name
      id: jarname
      run: echo "##[set-output name=jarname;]$(find build/libs/ -name "*.jar" -not -name "*all*" -not -name "*source*" | sed 's:.*/::')"

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.3
      with:
          name: ${{ steps.jarname.outputs.jarname }}
          path: ./build/libs/
